# WARNING: The list bellow contains offensive words.

"""
PROFANITY_WORD_LIST can be used to check for offensive content in user input.
This list may contain common words, so it should not be used to block content, but rather filter and flag to warn admin(s) to review it.
As any black-list, this is not exaustive and may only catch very common profanity.
"""

PROFANITY_WORD_LIST = [
    "apeshit",
    "arschloch",
    "ash0le",
    "ash0les",
    "asholes",
    "assfuck",
    "assfucker",
    "assfukka",
    "assgoblin",
    "assh0le",
    "assh0lez",
    "assho1e",
    "asshole",
    "asskiss",
    "asskisser",
    "assklown",
    "asslick",
    "asslover",
    "assman",
    "assmaster",
    "assmonkey",
    "assshit",
    "assshole",
    "asssucker",
    "asswhole",
    "asswhore",
    "b a s t a r d",
    "b i t c h",
    "b o o b",
    "b!+ch",
    "b!tch",
    "b!tchin",
    "b*tch",
    "b00b",
    "b00bies",
    "b00biez",
    "b00bs",
    "b00bz",
    "b17ch",
    "b1tch",
    "b7ch",
    "badfuck",
    "bagging",
    "ball gag",
    "ball gravy",
    "ball kicking",
    "ball licking",
    "ball sack",
    "ball sucking",
    "ballbag",
    "balllicker",
    "ballsack",
    "bang",
    "barfface",
    "bdsm",
    "beatyourmeat",
    "beaver cleaver",
    "beaver lips",
    "beef curtains",
    "bi+ch",
    "bi7ch",
    "biatch",
    "big tits",
    "bimbo",
    "bimbos",
    "bitch",
    "bitchass",
    "bitched",
    "bitcher",
    "blow job",
    "blowjob",
    "booobs",
    "boooobs",
    "booooobs",
    "booooooobs",
    "btch",
    "bumfuck",
    "buttbang",
    "buttcheeks",
    "buttface",
    "buttfuck",
    "buttfucker",
    "buttfuckers",
    "butthead",
    "butthole",
    "c u n t",
    "c-0-c-k",
    "c-o-c-k",
    "c-u-n-t",
    "c.0.c.k",
    "c.o.c.k.",
    "c.u.n.t",
    "c0ck",
    "c0cks",
    "c0cksucker",
    "c0k",
    "christ killer",
    "clitface",
    "clitfuck",
    "cock-sucker",
    "cocksuck",
    "cum face",
    "cum licker",
    "cuntface",
    "cuntfuck",
    "d0ng",
    "d0uch3",
    "d0uche",
    "d1ck",
    "d1ld0",
    "d1ldo",
    "deapthroat",
    "deep throat",
    "dick pic",
    "dickfuck",
    "dickhead",
    "dild0",
    "dog style",
    "dog-fucker",
    "doggie",
    "doggy",
    "double penetration",
    "doublepenetration",
    "douche",
    "dumb",
    "dumshit",
    "eat my ass",
    "eatmyass",
    "eatpussy",
    "f u c k",
    "f u k",
    "f*ck",
    "f-u-c-k",
    "f.u.c.k",
    "f_u_c_k",
    "facefucker",
    "faggot",
    "fingerbang",
    "fingerfuck",
    "fistfuck",
    "hitler",
    "hotdamn",
    "hotpussy",
    "hotsex",
    "how to kill",
    "how to murder",
    "howtokill",
    "iblowu",
    "j3rk0ff",
    "jack off",
    "jack-off",
    "jackass",
    "jackhole",
    "jackoff",
    "jackshit",
    "masterbate",
    "motha",
    "mother fucker",
    "motherfucker",
    "motherfuck",
    "mutha",
    "nazi",
    "negro",
    "nig",
    "niig",
    "nipple",
    "orgasm",
    "orgies",
    "orgy",
    "p e n i s",
    "p i s",
    "p u s s y",
    "p.u.s.s.y.",
    "p0rn",
    "paedophile",
    "pedo",
    "pen1s",
    "penetrate",
    "penetration",
    "peni5",
    "penial",
    "penile",
    "penis",
    "perv",
    "phone sex",
    "phonesex",
    "pi55",
    "pigfucker",
    "pising",
    "pisof",
    "piss",
    "porn",
    "pr1c",
    "pr1ck",
    "pr1k",
    "prick",
    "prostitute",
    "pu55i",
    "pu55y",
    "pusies",
    "pussy",
    "puta",
    "puto",
    "rape",
    "recktum",
    "rectal",
    "rectum",
    "rectus",
    "redlight",
    "redneck",
    "ritard",
    "rtard",
    "s h i t",
    "s hit",
    "s-h-1-t",
    "s-h-i-t",
    "s-o-b",
    "s.h.i.t.",
    "s_h_i_t",
    "scheiss",
    "schlampe",
    "schmuck",
    "schvartse",
    "schwartze",
    "sex",
    "sh!+",
    "sh!t",
    "sh1t",
    "shag",
    "shaved",
    "shemale",
    "shhit",
    "shit",
    "skumbag",
    "slut",
    "son of",
    "son-of",
    "sonof",
    "sperm",
    "stupid",
    "suck",
    "t i t",
    "t1t",
    "tit"
    "topless",
    "tramp",
    "trannie",
    "tranny",
    "transsexual",
    "transvestite",
    "trashy",
    "tw4t",
    "twat",
    "v a g i n a",
    "v14gra",
    "v1gra",
    "vag1na",
    "vagiina",
    "vaj1na",
    "vibrator",
    "vigra",
    "vulva",
    "wet dream",
    "wetdream",
    "wetspot",
    "wh00r",
    "wh0re",
    "wh0reface",
    "white power",
    "white trash",
    "whitey",
    "whore",
    "wuss",
    "x-rated",
    "xrated",
    "xxx",
    "yank",
    "yourboobs",
    "yourpenis",
    "yourtits",
    "zoophil",
    "🖕"
]