COMMON_SPAM_WORDS_IN_SUBJECT =[
    "$",
    "account",
    "billing",
    "confidential",
    "deal",
    "dollar",
    "earn",
    "free",
    "grow",
    "limited time",
    "meeting",
    "money",
    "now",
    "offer",
    "opportunity",
    "order",
    "password",
    "payroll",
    "perfect",
    "profit",
    "reset",
    "soon",
    "the best",
    "the best",
    "unbelievable",
    "waiting"
]

MOST_COMMON_SPAM_WORDS = [
"$",
"% off",
"100% free",
"4u",
"act now"
"as seen on",
"avoid bankruptcy",
"bargain",
"be your own boss",
"beneficiary",
"best price",
"big bucks",
"billing address",
"billion dollars",
"buy",
"call free",
"call now",
"cards accepted",
"cents on the dollar",
"chance",
"check",
"check or money order",
"claims",
"clearance",
"click below",
"click here",
"collect",
"collect child support",
"compete for your business",
"consolidate debt and credit",
"consolidate your debt",
"cost",
"credit",
"credit bureau",
"credit card",
"credit check",
"dear friend",
"deal",
"discount",
"dormant",
"double your",
"earn",
"easy terms",
"eliminate bad credit",
"eliminate debt",
"expect to earn",
"explode your business",
"extra income",
"fast cash",
"financial",
"financially independent",
"for just",
"free",
"free consultation",
"full refund",
"get out of debt",
"get paid",
"gift certificate",
"giving away",
"guarantee",
"have you been turned down?",
"hidden assets",
"hidden charges",
"home employment",
"home-based",
"home-based business",
"human growth hormone",
"important information",
"in accordance with laws",
"income",
"increase sales",
"increase traffic",
"increase visibility",
"info you requested",
"information you requested",
"insurance",
"investment",
"investment decision",
"join millions",
"lifetime",
"life insurance",
"lose weight",
"lowest price",
"make money",
"meet singles",
"million",
"million dollars",
"money",
"money back",
"money making",
"mortgage",
"most common spam words",
"multi-level marketing",
"near you",
"no age restrictions",
"no cost",
"no fees",
"no obligation",
"no-obligation",
"offer",
"offer expires",
"online biz opportunity",
"online degree",
"online marketing",
"online pharmacy",
"opt-in",
"order",
"pennies a day",
"per day",
"per week",
"password",
"payroll",
"perfect",
"perfumes",
"personality",
"potential earnings",
"pre-approved",
"price",
"prize",
"priority mail",
"produced and sent out",
"profit",
"quote",
"refinance",
"refinance home",
"removal instructions",
"reserves the right",
"sale",
"save",
"score with babes",
"serious cash",
"sent in compliance",
"shopping spree",
"sign up",
"social security number",
"special promotion",
"spending spree",
"stock alert",
"stock disclaimer statement",
"stock pick",
"stop snoring",
"stuff on sale",
"subject to credit",
"subscribe",
"tastes great",
"terms and conditions",
"the best rates",
"the following form",
"they’re just giving it away",
"this won’t last",
"thousands",
"to be removed",
"to our loyal customers",
"trial",
"trial offer",
"unbelievable",
"unlimited",
"unsolicited",
"unsecured credit",
"unsecured debt",
"university diplomas",
"us dollars",
"vacation",
"valium",
"viagra",
"vicodin",
"visit our website",
"wait",
"weekend getaway",
"we honor all",
"what are you waiting for?",
"while supplies last",
"who really wins?",
"why pay more?",
"will not believe your eyes",
"win",
"winner",
"won",
"work at home",
"work from home",
"xanax",
"you have been selected",
"you've been selected",
"you’re a winner!",
"your chance"
]


